### ISSUE TITLE
Define structure externally

### ISSUE THREAD

**Issue by shaib** [shaib/sheelon#2]
The data came in, so far, in CSV files with two header rows.
"Chapters" were always defined in first row, but some questions were also defined in first row (with 2nd row "response" or "אנא ענו") and some questions (the pick-3-of-many kind) had the question in row 1, and headers for boolean options in row 2.

We need a way to define, outside the CSV file, the structure.

Tentative structure: (example in YAML format)

```yaml
Chapter 1:
    question 1: "1-5"
    question 2: "1-5-rev"
    question 3: "text"
    question 4:  # a list of options, indicates they're all boolean and this is a "pick 3"
        - option a
        - option b
        - option c
    Chapter 1 index: "compute"
Chapter 2:
    # ...
```
Or, in Hebrew:

```yaml
פרק א:
    שאלה א: "חמש"
    שאלה ב: "חמש-הפוך"
    שאלה ג: טקסט
    שאלה ד:
        - אופציה 1
        - אופציה 2
        - אופציה 3
    מדד פרק א: מחושב
פרק ב:
    # ...
``` 
    
In this, the values `1-5`, `1-5-rev` `text`, `compute` and of course their Hebrew versions are constants representing the type of question.
The CSV file can then have:
- For "pick 3", set of option questions -- question title in row 1, options in row 2
- For other questions, title in row 1 or 2, other row required to be empty or one of a set of known strings (like "Response").
